name: CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: linux (py=${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
<<<<<<< HEAD
        python-version:
          - "3.11"
          - "3.12"
||||||| parent of 9d52d28 (ci: set PYTHONPATH=src for pytest; keep Windows optional)
        python-version: ['3.11','3.12']
    name: linux (py=${{ matrix.python-version }})
=======
        python-version: ["3.11","3.12"]
>>>>>>> 9d52d28 (ci: set PYTHONPATH=src for pytest; keep Windows optional)
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - run: python -m pip install -U pip
      - run: pip install ruff black pytest mypy
      - run: ruff check .
      - run: black --check .
      - run: pytest -q
      - run: mypy .

  windows_optional:
    name: windows (optional)
    runs-on: windows-latest
    continue-on-error: true
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
<<<<<<< HEAD
        with:
          python-version: "3.12"
||||||| parent of 9d52d28 (ci: set PYTHONPATH=src for pytest; keep Windows optional)
        with:
          python-version: ${{ matrix.python-version }}
=======
        with: { python-version: "3.12" }
>>>>>>> 9d52d28 (ci: set PYTHONPATH=src for pytest; keep Windows optional)
      - run: python -m pip install -U pip
      - run: pip install ruff black pytest mypy
      - run: ruff check .
      - run: black --check .
      - run: pytest -q
      - run: mypy .
